// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnutfichtbuzrgdypjhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudXRmaWNodGJ1enJnZHlwamhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MDM5MzgsImV4cCI6MjA1MzE3OTkzOH0.orSkOhg0nv1IZ8uitNRzYVGq673BoR47q3q3JtzvaB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);